### ISSUE TITLE
Project update from git always fails

### ISSUE THREAD

**Issue by matthias-prog** [ansible/tower-operator#1457]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When adding a Project with source control type git the source control update always fails. The update also fails when manually triggering the update after the automatic one fails, also fails.

### AWX Operator version

2.0.0

### AWX version

22.0.0

### Kubernetes platform

openshift

### Kubernetes/Platform version

4.11

### Modifications

no

### Steps to reproduce

Projects >> Add >> Source Control Type: git, Source Control URL: <internal bitbucket> >> Save

or manually:

Projects >> "Sync Project"

### Expected results

Project Update completes sucessfully.

### Actual results

The Project Update fails on high project update verbosity with:
ansible-playbook [core 2.15.1rc1]
  config file = None
  configured module search path = ['/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.9.16 (main, Mar  7 2023, 00:00:00) [GCC 11.3.1 20221121 (Red Hat 11.3.1-4)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
No config file found; using defaults
host_list declined parsing /tmp/awx_44_cqxenjqy/inventory/hosts as it did not pass its verify_file() method
script declined parsing /tmp/awx_44_cqxenjqy/inventory/hosts as it did not pass its verify_file() method
auto declined parsing /tmp/awx_44_cqxenjqy/inventory/hosts as it did not pass its verify_file() method
Parsed /tmp/awx_44_cqxenjqy/inventory/hosts inventory source with ini plugin
Skipping callback 'awx_display', as we already have a stdout callback.
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: project_update.yml ***************************************************
3 plays in project_update.yml

PLAY [Update source tree if necessary] *****************************************

TASK [Update project using git] ************************************************
task path: /tmp/awx_44_cqxenjqy/project/project_update.yml:41
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: 1006770000
<127.0.0.1> EXEC /bin/sh -c 'echo ~1006770000 && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /runner/.ansible/tmp `"&& mkdir "` echo /runner/.ansible/tmp/ansible-tmp-1687423825.0370514-1143-61689420573110 `" && echo ansible-tmp-1687423825.0370514-1143-61689420573110="` echo /runner/.ansible/tmp/ansible-tmp-1687423825.0370514-1143-61689420573110 `" ) && sleep 0'

### Additional information

[project_update_44.txt](https://github.com/ansible/awx-operator/files/11832278/project_update_44.txt)
[awx.txt](https://github.com/ansible/awx-operator/files/11832356/awx.txt)
[task-deployment.txt](https://github.com/ansible/awx-operator/files/11832358/task-deployment.txt)
[web-deployment.txt](https://github.com/ansible/awx-operator/files/11832359/web-deployment.txt)

**Comment by matthias-prog** [comment]
Quite bizarelly, this issue has been resolved by an update to operator version 2.2.1 and update to awx 22.3.0.

**Comment by matthias-prog** [comment]
This issue is now occuring again, after an update from 22.3.0 to 22.5.0 and an operator update to 2.4.0.
Manually setting the awx image to 22.3.0 in the AWX CR does not change anything.

I have found somethin in the log of awx-ee in the task pod:
INFO 2023/07/18 14:35:24 Running control service control
INFO 2023/07/18 14:35:24 Initialization complete
WARNING 2023/07/18 14:35:35 Reload not successful: a non-reloadable config action 'work-signing' was modified or added. Must restart receptor for these changes to take effect
ERROR 2023/07/18 14:35:57 write unix /var/run/receptor/receptor.sock->@: write: broken pipe
ERROR 2023/07/18 14:35:57 Write error in control service: write unix /var/run/receptor/receptor.sock->@: write: broken pipe
WARNING 2023/07/18 14:36:18 Could not read in control service: read unix /var/run/receptor/receptor.sock->@: use of closed network connection
WARNING 2023/07/18 14:36:18 Could not close connection: close unix /var/run/receptor/receptor.sock->@: use of closed network connection
ERROR 2023/07/18 14:37:15 Error updating status file /tmp/receptor/test1-awx-task-7b97c5db87-4rh2w/E0MbZVxM/status: open /tmp/receptor/test1-awx-task-7b97c5db87-4rh2w/E0MbZVxM/status.lock: no such file or directory.
ERROR 2023/07/18 14:37:18 Exceeded retries for reading stdout /tmp/receptor/test1-awx-task-7b97c5db87-4rh2w/E0MbZVxM/stdout
WARNING 2023/07/18 14:37:19 Could not read in control service: read unix /var/run/receptor/receptor.sock->@: use of closed network connection
WARNING 2023/07/18 14:37:19 Could not close connection: close unix /var/run/receptor/receptor.sock->@: use of closed network connection
WARNING 2023/07/18 14:37:41 Could not read in control service: read unix /var/run/receptor/receptor.sock->@: use of closed network connection
WARNING 2023/07/18 14:37:41 Could not close connection: close unix /var/run/receptor/receptor.sock->@: use of closed network connection
WARNING 2023/07/18 14:40:08 Could not read in control service: read unix /var/run/receptor/receptor.sock->@: use of closed network connection
WARNING 2023/07/18 14:40:08 Could not close connection: close unix /var/run/receptor/receptor.sock->@: use of closed network connection

**Comment by kplumen** [comment]
This is still an open issue with 23.3.0 AWX version.. I tried every single possible option with Gitlab to Gihub repos with SSH keys and Git PAT but it keeps hitting error.

**Comment by kplumen** [comment]
I tried CentOS 9, Ubuntu 22.04 with single node kubernetes but even 23.3.1 is giving same error.. any clue where am I falling apart? I tried classic token, new PAT token from Github, somehow, it's not working and giving same error over and over... I tried ssh keys as well, still same. I switched to GitLab for repos but no change.

**Comment by joewortmankofax** [comment]
I'm trying to do the same thing and having the same issue. I am using a single node K8s minikube setup and Ubuntu 20.04 and still have a connection time out error when using a PAT to connect to GitHub, even though I can curl the same URL from the ubuntu host.

**Comment by joewortmankofax** [comment]
> This issue is now occuring again, after an update from 22.3.0 to 22.5.0 and an operator update to 2.4.0. Manually setting the awx image to 22.3.0 in the AWX CR does not change anything.
> 
> I have found somethin in the log of awx-ee in the task pod: INFO 2023/07/18 14:35:24 Running control service control INFO 2023/07/18 14:35:24 Initialization complete WARNING 2023/07/18 14:35:35 Reload not successful: a non-reloadable config action 'work-signing' was modified or added. Must restart receptor for these changes to take effect ERROR 2023/07/18 14:35:57 write unix /var/run/receptor/receptor.sock->@: write: broken pipe ERROR 2023/07/18 14:35:57 Write error in control service: write unix /var/run/receptor/receptor.sock->@: write: broken pipe WARNING 2023/07/18 14:36:18 Could not read in control service: read unix /var/run/receptor/receptor.sock->@: use of closed network connection WARNING 2023/07/18 14:36:18 Could not close connection: close unix /var/run/receptor/receptor.sock->@: use of closed network connection ERROR 2023/07/18 14:37:15 Error updating status file /tmp/receptor/test1-awx-task-7b97c5db87-4rh2w/E0MbZVxM/status: open /tmp/receptor/test1-awx-task-7b97c5db87-4rh2w/E0MbZVxM/status.lock: no such file or directory. ERROR 2023/07/18 14:37:18 Exceeded retries for reading stdout /tmp/receptor/test1-awx-task-7b97c5db87-4rh2w/E0MbZVxM/stdout WARNING 2023/07/18 14:37:19 Could not read in control service: read unix /var/run/receptor/receptor.sock->@: use of closed network connection WARNING 2023/07/18 14:37:19 Could not close connection: close unix /var/run/receptor/receptor.sock->@: use of closed network connection WARNING 2023/07/18 14:37:41 Could not read in control service: read unix /var/run/receptor/receptor.sock->@: use of closed network connection WARNING 2023/07/18 14:37:41 Could not close connection: close unix /var/run/receptor/receptor.sock->@: use of closed network connection WARNING 2023/07/18 14:40:08 Could not read in control service: read unix /var/run/receptor/receptor.sock->@: use of closed network connection WARNING 2023/07/18 14:40:08 Could not close connection: close unix /var/run/receptor/receptor.sock->@: use of closed network connection

How do you check these logs? I can't find the admin password to get sudo privileges once inside the task container.
