### ISSUE TITLE
wrong indent on task.yaml.j2 for security_context_settings section

### ISSUE THREAD

**Issue by romankuzmik** [ansible/tower-operator#1588]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

cc-awx-operator/roles/installer/templates/deployments/task.yaml.j2
```
{% if security_context_settings|length %}
        {{ security_context_settings | to_nice_yaml | indent(10) }}
{% endif %}
```
->
```
{% if security_context_settings|length %}
        {{ security_context_settings | to_nice_yaml | indent(8) }}
{% endif %}
```

### AWX Operator version

2.7.0

### AWX version

23.3.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

v1.24.9

### Modifications

no

### Steps to reproduce

Perform fresh install with AWX manifest containing security_context_settings:
```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
 ...
  security_context_settings:
    fsGroup: 0
    fsGroupChangePolicy: OnRootMismatch
    runAsGroup: 0
    runAsUser: 0
```

### Expected results

aws-task deployment to be created

### Actual results

```
TASK [installer : Apply deployment resources] **********************************
task path: /opt/ansible/roles/installer/tasks/resources_configuration.yml:248
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:                                  ^
failed: [localhost] (item=task) => {\"ansible_loop_var\": \"item\", \"changed\": false, \"item\": \"task\", \"msg\": \"Failed to load resource definition: mapping values are not allowed here\
  in \\\"<unicode string>\\\", line 211, column 30:\
              fsGroupChangePolicy: OnRootMismatch\
                                 ^\"}
ok: [localhost] => (item=web) => {\"ansible_loop_var\": \"item\", \"c
```

**Comment by rchaud** [comment]
I can validate this issue. I am also having the same error when using security_context_settings. It seems the indentation is incorrect. 

```installer : Apply deployment resources] **********************************
task path: /opt/ansible/roles/installer/tasks/resources_configuration.yml:248
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:                         ^
failed: [localhost] (item=task) => {\"ansible_loop_var\": \"item\", \"changed\": false, \"item\": \"task\", \"msg\": \"Failed to load resource definition: mapping values are not allowed here\\n  in \\\"<unicode string>\\\", line 209, column 21:\\n              runAsGroup: 0\\n                        ^\"}\n```

**Comment by romankuzmik** [comment]
fixed as of https://github.com/ansible/awx-operator/commit/39bebe64ba9e2a2b9732037cccd9684014b0a14d

**Comment by travisghansen** [comment]
ETA on getting this in a release?

**Comment by rooftopcellist** [comment]
@travisghansen There is a new version of the awx-operator available with these changes now (2.7.1).

**Comment by vivekshete9** [comment]
This is still an issue in awx-operator 2.16.1 and awx v24.3.1. Reported issue [1850](https://github.com/ansible/awx-operator/issues/1850)

**Comment by vivekshete9** [comment]
running below command on awx-web pod helped to spin up task pod correctly. However I am not able to use `awx-admin-password` secrets to login to the tower UI.

`awx-manage migrate --noinput`

**Comment by vivekshete9** [comment]
Running below command on web pod helped

`kubectl exec pod/<awx_pod_name> --container awx-web -it awx-manage createsuperuser`
